### ISSUE TITLE
Rectangles not rendered on Canvas when moved

### ISSUE THREAD

**Issue by TillWenke** [hpi-swa-teaching/SVGMorph#60]
![image](https://user-images.githubusercontent.com/38500891/174429327-1b546b2f-50a8-4c1e-9a1f-ac60ade6fea9.png)
![image](https://user-images.githubusercontent.com/38500891/174429333-db40479c-afc8-4641-8a56-d7c04b1c8d7a.png)

**Comment by Nils1729** [comment]
Is this still open? Can't reproduce.
